FROM telegraf:1.25

COPY requirements.txt /tmp/requirements.txt

RUN apt-get update && apt-get install -y python3 python3-pip && \
    pip3 install -r /tmp/requirements.txt && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
